hashedPassword: ENC[AES256_GCM,data:g4PjoNHYxicKcAbsCjecIfwSZunj0uqyxKi2RbyRuFa0T2s+VdgvCxygVVj8LDTVX37YO6cRe1ZDQs0fzNSwy/OhVvrpVaocXw==,iv:1oMZGtMhfRWp1nr1Td1Yv7gnFZxjHkxnb+idLbTh4Nc=,tag:arOcPlX3vhvuASu5U6py+g==,type:str]
sops:
    age:
        - recipient: age17sdp0gguexd88qel74fa4zeckxh93gqpkayz366fz6yvjauw7vcq7w6y45
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLdzBYdlZiQXZpNVVkMSs0
            QzdtTU82bzFsSHlPY2tSYVB4THFZbmxyVUdzCkZqODVEZlRSSm9SMnFmZnhKTk5U
            WEh3V1Zua1QyNTlvVGRHNktyQi9ualUKLS0tIGZFaEIxT0NVZTkvOXZQNFI5VTlP
            TDM5czFEc1lCU281R0NKQkQ1bjNLL0kKHtVBtagNiz2fyyudwBJpxhfQBUMt++Be
            tE1SGo+TirLPCgFK/ynw2zXUj7IZ8+qANOpGmStroUBgJGfoEHHlwg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jv3t4pltlsympq86vjhjjr66hvm25hv9utlk2nwa99qxfapc2amq2vmkel
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWL2dOcWpFWnZXYWdOZzhx
            Z1hLUnRzTXo4N21ESXd6N1VhTVZUVVNHSFNNCnE2QkJ5clQvaExyY2dWMUZic3RI
            NVJyVUNFZXdOTktjQ2ZYT0xER2x6Z1EKLS0tIHQxTFFTYlVnYjdiRUZnQXRDWHVB
            WHVZYkQvN1MxaEV4NElLcHFPZmNjZVkKbUHXfK4Wt7MRS2XYBy9v/SQ3a6T4V5FK
            bjd0nVVTJeMnE6V9avjNuOCVUkug4PylIzSMSohfpR6AmSy68jYElw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-31T02:40:58Z"
    mac: ENC[AES256_GCM,data:ZO+UGKpTWl2WTMQb5nCcqrC/T/Yls4EnpvF58Gt46nXRtEEwlkmG4lvQNOUP2t4fsyJ2fVSfbWlnPAOCO8kzcK5831bMblSonH52qXhLg26fdtvsGwYz1oReKtwXx20OK/lM9+nABBZFEKpqEtuvi3vLCpOANNdDkF3Cg8VYwu4=,iv:Wx2YEpXpZX0MKlL0zvrPLcgdmRCshdlEQokMmQe2gBM=,tag:0lPwq2LYM1dWYolBoEA5SQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
